# serverless.yml

service: bnt-reports-management

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 14
  arnHostNumber: 920871934450
  deploymentBucket: bidwiser-lambda-layers
  memorySize: 1024
  timeout: 10
  apiName: budwiserdev
  environment:
    stage: ${opt:stage, 'dev'}
    region: us-east-1
    arnHostNumber: 920871934450
    reportDBName: reports
    consumerDBName: consumers
    userDBName: users
    userAuthDBName: user_auth
    divisionDBName: divisions
    subDivisionDBName: sub_divisions
    circleDBName: circles
    fileUploadBucket: bw-${self:provider.stage}-image-bucket
    notificationDBName: notifications
    #dbURL: postgresql://bentek:Q4BLF1znoIh1f3RM8P842g@free-tier12.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dbentek-dev-636
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
            - 'lambda:AddPermission'
          Resource: "arn:aws:lambda:*:*:*"

        - Effect: 'Allow'
          Action:
            - 'events:PutRule'
            - 'events:PutTargets'
          Resource: "arn:aws:events:*:*:*"

 
functions:

  fetchReports:
    handler: src/index.handler
    events:
      - http:
          path: /report/{reportId}
          method: get
          cors: true
  
  fetchReportsConditionaly:
    handler: src/index.handler
    events:
      - http:
          path: /report/search/condition
          method: get
          cors: true

  fetchReportCountByAgent:
    handler: src/index.handler
    events:
      - http:
          path: /report/count/agent/{agentId}
          method: get
          cors: true

  fetchReportsByAgent:
    handler: src/index.handler
    events:
      - http:
          path: /report/agent/{agentId}
          method: get
          cors: true
  
  createReport:
    handler: src/index.handler
    events:
      - http:
          path: /report/
          method: post
          cors: true
          documentation: ${file(src/spec/models/serverless.doc.yml):endpoints.createAuctions}
  
  getBulkReportData:
    handler: src/index.handler
    events:
      - http:
          path: /report/get-data/send-mail
          method: get
          cors: true
  
  # processReportDBData:
  #   handler: src/services/DataService.getBulkReportData
plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
  - serverless-plugin-reducer
  - serverless-layers
  - serverless-offline
  #- serverless-openapi #serverless openapi generate -o ../apidoc/specs/auctions-openapi.yml

custom:
  prod:
    Stack: bwTestAPI
    LogLevel: info
    COGNITO_USER_POOL_ID: us-east-1_yI0clNULa
    COGNITO_CLIENT_ID: 5308sab6hbd1jkc7n19k4r4b5q
    # ApiHostedZone: examplesite.us.
    # ApiSite: "prod.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  dev:
    Stack: bwTestAPI
    LogLevel: debug
    COGNITO_USER_POOL_ID: us-east-1_yI0clNULa
    COGNITO_CLIENT_ID: 5308sab6hbd1jkc7n19k4r4b5q
    # ApiHostedZone: examplesite.us.
    # ApiSite: "dev.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  dotenv:
    path: ../.env.${self:provider.stage}
  serverless-layers:
    # applies for all lambdas 
    # layersDeploymentBucket: bw-auction-layer #${self:provider.stage}-bw-auctions-layer
    dependenciesPath: ./package.json
  
  