# serverless.yml

service: bw-fb-management

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 14
  arnHostNumber: 920871934450
  deploymentBucket: bidwiser-lambda-layers
  memorySize: 2048
  timeout: 900
  apiName: budwiserdev
  environment:
    stage: ${opt:stage, 'dev'}
    accessKeyId: AKIA5M2B6THZDQ5UPGMC
    secretAccessKey: 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
    region: us-east-1
    arnHostNumber: 920871934450
    fileUploadBucket: ${self:custom.${self:provider.stage}.fileUploadBucket}
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
            - 'lambda:AddPermission'
          Resource: "arn:aws:lambda:*:*:*"

        - Effect: 'Allow'
          Action:
            - 'events:PutRule'
            - 'events:PutTargets'
          Resource: "arn:aws:events:*:*:*"


functions:
  getData:
    handler: src/index.handler
    iamRoleStatements:
      - Effect: 'Allow'
        Action:
          - 'lambda:InvokeFunction'
        Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:bw-fb-management-${self:provider.stage}-processFBData
    events:
      - http:
          path: /fb/get-data
          method: get
          cors: true
  processFBData:
    handler: src/services/DataService.getFBData
          
plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-reducer
  - serverless-layers
  - serverless-offline


custom:
  prod:
    Stack: BidwiserApi
    LogLevel: info
    fileUploadBucket: bw-${self:provider.stage}-image-bucket
    # ApiHostedZone: examplesite.us.
    # ApiSite: "prod.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  dev:
    Stack: BidwiserApi
    LogLevel: debug
    fileUploadBucket: bw-${self:provider.stage}-image-bucket
    # ApiHostedZone: examplesite.us.
    # ApiSite: "dev.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  serverless-layers:
    # applies for all lambdas 
    # layersDeploymentBucket: bw-auction-layer #${self:provider.stage}-bw-auctions-layer
    dependenciesPath: ./package.json
    # CompatibleArchitectures: null
