# serverless.yml

service: bnt-division-management

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  logRetentionInDays: 14
  arnHostNumber: 920871934450
  deploymentBucket: bidwiser-lambda-layers
  memorySize: 2024
  timeout: 19
  apiName: budwiserdev
  environment:
    stage: ${opt:stage, 'dev'}
    region: us-east-1
    arnHostNumber: 920871934450
    divisionDBName: divisions
    subDivisionDBName: sub_divisions
    #dbURL: postgresql://bentek:Q4BLF1znoIh1f3RM8P842g@free-tier12.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&options=--cluster%3Dbentek-dev-636
  apiGateway:
    restApiId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-restApiId-${self:provider.stage}
    restApiRootResourceId:
      'Fn::ImportValue': ${self:custom.${self:provider.stage}.Stack}-rootResourceId-${self:provider.stage}

  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:InvokeFunction'
            - 'lambda:AddPermission'
          Resource: "arn:aws:lambda:*:*:*"

        - Effect: 'Allow'
          Action:
            - 'events:PutRule'
            - 'events:PutTargets'
          Resource: "arn:aws:events:*:*:*"

 
functions:

  fetchDivisions:
    handler: src/index.handler
    events:
      - http:
          path: /divisions/get/
          method: get
          cors: true

  fetchDivisionsByCircle:
    handler: src/index.handler
    events:
      - http:
          path: /divisions/circle/{circleId}
          method: get
          cors: true

  createDivision:
    handler: src/index.handler
    events:
      - http:
          path: /divisions/
          method: post
          cors: true
          #documentation: ${file(src/spec/models/serverless.doc.yml):endpoints.createAuctions}

  createSubDivision:
    handler: src/index.handler
    events:
      - http:
          path: /divisions/sub-division
          method: post
          cors: true

  updateDivision:
    handler: src/index.handler
    events:
      - http:
          path: /divisions/{divisionId}
          method: patch
          cors: true
          #documentation: ${file(src/spec/models/serverless.doc.yml):endpoints.createAuctions}
  
plugins:
  - serverless-pseudo-parameters
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin
  - serverless-plugin-reducer
  - serverless-layers
  - serverless-offline
  #- serverless-openapi #serverless openapi generate -o ../apidoc/specs/auctions-openapi.yml

custom:
  prod:
    Stack: bwTestAPI
    LogLevel: info
    COGNITO_USER_POOL_ID: us-east-1_yI0clNULa
    COGNITO_CLIENT_ID: 5308sab6hbd1jkc7n19k4r4b5q
    # ApiHostedZone: examplesite.us.
    # ApiSite: "prod.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  dev:
    Stack: bwTestAPI
    LogLevel: debug
    COGNITO_USER_POOL_ID: us-east-1_yI0clNULa
    COGNITO_CLIENT_ID: 5308sab6hbd1jkc7n19k4r4b5q
    # ApiHostedZone: examplesite.us.
    # ApiSite: "dev.examplesite.us"
    # ApiCert: "arn:aws:acm:us-east-1:12345678901:certificate/12345678-b123-a123-c123-abcd1234efgh"
  dotenv:
    path: ../.env.${self:provider.stage}
  serverless-layers:
    # applies for all lambdas 
    # layersDeploymentBucket: bw-auction-layer #${self:provider.stage}-bw-auctions-layer
    dependenciesPath: ./package.json
  
  